### ISSUE TITLE
Prioritise last episode source (suggestion)

### ISSUE THREAD

**Issue by ahmedashed** [Goldenfreddy0703/Otaku#106]
Hi again, thank you for continuing to improve on this amazing anime add-on.

One suggestion is to have the feature, that's the same as seren, to prioritise the last selected source of the show. This could solve the episode/season naming issue as well for some shows. 

Here is an example of where it could be applied

Scraping fire force season 2 with dub as the preferred source brings up three sources for me. The one that gets picked automatically, due to my dub priority list, is season 1 source, even though season 2 dub sources are right below it. A prioritise last source feature would make it so I select the correct source once, then it will be automated for the rest of the episodes in that session. Additionally there will be different versions with certain .ASS subs and so on that the user might want to prioritise over others. Let me know what you think of this feature

Thanks for all your hard work!

**Comment by Goldenfreddy0703** [comment]
Oh I think I kinda see what you mean and it sounds like a great idea but say I was on season 1 on an anime but I had prioritize last season on, then it would be a mess. In the future, @jkaw will be improving scrapping or maybe @Gujal00 will but again I'm not too sure depending on the debrid and all. 

For now, you may wanna use embeds, 9anime started working again so it maybe your best bet in order to find the right episode and all for you.

**Comment by Goldenfreddy0703** [comment]
Hey so, I have been thinking about this and i think it could be useful to to have to prioritize season by torrent, i may look into this more and see if i can add a way where the user to input the season number where they can prioritize season by torrent. Thank you for the suggestion.

**Comment by Goldenfreddy0703** [comment]
Hey so good news, i finally figured out a way to to prioritize by season number. In the future, we will have this released very soon once our branch enime-fallback is added very soon. 

Im gonna close this but we will release very soon hopefully.
Thank you
