### ISSUE TITLE
No 9anime results

### ISSUE THREAD

**Issue by Thor4201** [Goldenfreddy0703/Otaku#113]
I'm not sure if this is an issue from consumet but I haven't seen any 9 anime results in Awhile, as far as consumet I wouldn't know what to look for right now, if there is anything that can be done to resolve it that'd be great, I'll have a little more browse to see if I can see anything in mean time, if it's sorted before I figure it out, great..

**Comment by Goldenfreddy0703** [comment]
Hey so recently 9anime stopped working for consumet a few days ago so now consumet has a new challenge to face. 9anime is dumb cause they always change there decryption method and they are the worst so it will probably take a few days to get this figured out. In the meantime, Zero is the second best option that will give you good sources.

**Comment by Thor4201** [comment]
Hey great to hear, and yea I much like zoro compared to the others for a lot of stuff, on a completely different subject if you don't mind haha, I searched for sword art online it errors out and doesn't load anything, sword art online ii loads results.

**Comment by Goldenfreddy0703** [comment]
Hey so consumet will be shutting down very soon sadly but we will still have zoro sources which is good and you can always self host it as well. Im not sure if consumet will look into 9anime but if they do, thats great. Im going to go ahead and close this as well but hopefully zoro is still embed to use.

**Comment by Thor4201** [comment]
Hey I know this is closed, I've been messing around a bit again , I'm self hosting consumet for myself and wondering if perhaps it's searching a different location for consumet now I'm doing further testing http://localhost:3000/meta/anilist/info/129196?provider=9anime/watch/159331 this works in the browser not sure if it would help you guys

**Comment by Goldenfreddy0703** [comment]
Hey so i don't think so sadly, yesterday i came up with a list of providers that work and don't work and most providers are not working cause everyone is so busy to update the consumet api themselves. Hopefully they will do some fixes in the future on them but again, im not too sure. 

Here the list of providers i came up with, Im using spy x family for them.

Self Host Consumet Bugs with one Anilist ID:

-9anime: (Not Working due to 9anime devs)
Subs: http://localhost:3000/meta/anilist/info/140960?provider=9anime

Dubs: http://localhost:3000/meta/anilist/info/140960?provider=9anime&dub=true

-AnimeFox: (Not Working as usual but getting error message: "Error: connect ETIMEDOUT 75.2.18.233:443")
Subs: http://localhost:3000/meta/anilist/info/140960?provider=animefox

Dubs: http://localhost:3000/meta/anilist/info/140960?provider=animefox&dub=true

-Animepahe: (Not Working due to status code 521)
Subs: http://localhost:3000/meta/anilist/info/140960?provider=animepahe

Dubs: http://localhost:3000/meta/anilist/info/140960?provider=animepahe&dub=true

-BiliBili: (Never Working)
Subs: http://localhost:3000/meta/anilist/info/140960?provider=bilibili

Dubs: http://localhost:3000/meta/anilist/info/140960?provider=bilibili&dub=true

-Crunchyroll: (Not Getting Developed Anymore Sadly)
Subs: http://localhost:3000/meta/anilist/info/140960?provider=crunchyroll

Dubs: http://localhost:3000/meta/anilist/info/140960?provider=crunchyroll&dub=true

-Enime: (Working)
Subs: http://localhost:3000/meta/anilist/info/140960?provider=enime

Dubs: Dubs not Supported

-GogoAnime: (Working)
Subs: http://localhost:3000/meta/anilist/info/140960?provider=gogoanime

Dubs: http://localhost:3000/meta/anilist/info/140960?provider=gogoanime&dub=true

-Zoro: (Working for Subs) (Does not show episode meta for Dubs)
Subs: http://localhost:3000/meta/anilist/info/140960?provider=zoro

Dubs: http://localhost:3000/meta/anilist/info/140960?provider=zoro&dub=true

-Marin: (Kinda Working, Shows no episode meta)
Subs: http://localhost:3000/meta/anilist/info/140960?provider=marin

Dubs: http://localhost:3000/meta/anilist/info/140960?provider=marin&dub=true

Marin - Not Showing Episode Meta
Zoro Dubs - Not Showing Episode Meta For Dubs
Animepahe - Not Working due to status code 521
AnimeFox - Not Working as usual but getting error message: "Error: connect ETIMEDOUT 75.2.18.233:443"
9anime - 9anime Devs always change everything

**Comment by Thor4201** [comment]
Is there a way to pull it like this? http://localhost:3000/meta/anilist/info/101167?provider=nineanime&dub=true 
http://localhost:3000/meta/anilist/info/128893?provider=nineanime&dub=true
This is "is it wrong to pick up girls in a dungeon? " and "Hells Paradise" or is that more on the consumet side?

**Comment by Goldenfreddy0703** [comment]
sadly i don't think so cause when trying to use nineanime, it only pulls gogoanime episode meta, it has to be 9anime.
