### ISSUE TITLE
Recently Watched Section - Widget Does not update

### ISSUE THREAD

**Issue by Hoplite-WAM** [Goldenfreddy0703/Otaku#116]
Hi,

I'm using Otaku with the Arctic Zephyr Reloaded skin. When I add the widget for the last watched show it does not update each time a new show is watched.

So for example, let's say I watch show A, and add the widget. It will display show A. If i now watch show B, it still shows show A as being the most recent. This only happens with the widget, not the actual Otaku menu.

Let me know if I can provide any other information.

Thank you

**Comment by Goldenfreddy0703** [comment]
This is a widget bug which is related to #29. We do not know how to fix the widget stuff when it comes to next up or recently watched.

**Comment by Goldenfreddy0703** [comment]
Hey so i looked into this more and it actually is not a widget bug, its more of a shortcut bug cause "Last Watched" is basically just where you left off. Any anime you watch basically creates a specific shortcut for that anime in which the "Last Watched" is shown so any anime you watch changes the shortcut everytime. I think in the future, i may implant a better system for "Last Watched" where we can make like the "current" menu item from watchlist. Hopefully i will figure out a solution someday. 

Btw i have a workaround for your issue, If you have a Watchlist connected to Anilist, Mal. or Kitsu, inside the watchlist is a menu item called "current" and you can use that as your widget so that way you can see the history of the anime you watched recently. Just make sure to adjust the sort order in watchlist settings and you should be golden. 
![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/4c3db3fa-fc47-4e2d-82f7-dec566ac8c01)

btw, im gonna close this but will keep this in mind.
Thank you.
