### ISSUE TITLE
Request in reguards to adult search filter

### ISSUE THREAD

**Issue by Thor4201** [Goldenfreddy0703/Otaku#117]
Would you guys be able to change the adult search filter to instead be included instead of a seperate search for adult anime's, so a person doesn't have to switch that setting off and on everytime, when looking for certain anime's that arent included in adult search. Eg redo of healer you have to turn on the adult search filter to find it in a search, then turn it off if you aren't searching for adult anime's would be nice to just turn it on and have the adult content included.

**Comment by Goldenfreddy0703** [comment]
Ok yes and no, adult anime is literally a bunch of nsfw graphical content and having that with regular animes would look weird. I wanted to combine it as well but from looking at it, it looked weird. Anilist separates there adult anime and it's not combined. For adult anime like redo the healer, what you can do is add that anime in your favorites catagory or to your watchlist so that way you can go to it instantly without any issues.

**Comment by Thor4201** [comment]
> Ok yes and no, adult anime is literally a bunch of nsfw graphical content and having that with regular animes would look weird. I wanted to combine it as well but from looking at it, it looked weird. Anilist separates there adult anime and it's not combined. For adult anime like redo the healer, what you can do is add that anime in your favorites catagory or to your watchlist so that way you can go to it instantly without any issues.

Ahh gotcha, that makes sense.thanks for replying and I appreciate your tip on what I can do for those certain shows. Thank you bud
