### ISSUE TITLE
Real debrid source not loading 

### ISSUE THREAD

**Issue by XHALOX18** [Goldenfreddy0703/Otaku#118]
So previously I was trying to watch dragon ball, superhero movie and it’s torrent sources were approximately 20 torrent files now it’s loading only seven and sometimes it doesn’t load any torrent at all only embed which I don’t understand with some anime's I tried it on, and I got all the source Torrent files then the next minute I close the app and open it up again and all of a sudden I’m not getting this said files I got previously help it’s annoying and yes I wiped the app clear cache rebuild etc I’ve done it all

**Comment by Goldenfreddy0703** [comment]
Uhhh that's cause torrent files are separated by dub or sub so that's why you don't see the total amount cause either subs or dubs are hiding due to how you configured advanced settings. 

Reason why some animes have torrents and some don't is probably due to scrapping, we hope to fix that very soon, if I were me, I would use embeds like zoro cause they are the best. Btw about your last problem I'm not sure why but best solution would check your addon settings, make sure nyaa is enabled, reauthorize real debrid and yeah. 

Here is some troubleshooting steps just incase you want to follow them. #15

**Comment by XHALOX18** [comment]
Well I must say the add on it good, yes but I don’t think the error is caused my how I configure the add-on because when I wipe rebuild or even clear the caches and take off the filters it only finds the embed I can say the embeds are good but not with everything anime sometimes it finds lower quality than what real-debrid has also some anime  I can’t even get 1 embed maybe it’s because it’s dub but I don’t want to seem like I whiner cause I appreciate the add-on but it would be nice to constantly get the debrid files available to me you know anyways thanks in advance

**Comment by ek19q** [comment]
I'm actually having the same issue. I'm not getting anything from real-debrid. I just switched to Verizon so I went through all of the troubleshooting steps: switched to Nya Alt, removed filters (although I'm not a dub watcher), wiped addon, rebuilt database, cleared caches, reinstalled Otaku, checked my real-debrid subscription, etc, etc. 

I know the anime I'm watching should have some torrents because I'm rewatching shows and previously before the switch they had plenty of torrents. I'm not sure if I'm missing something with all of my troubleshooting as I'm new to Verizon and don't really know what the issue could be. If anyone could point me in the right direction that would be great. 

I'm on a fire stick and I could send a log if needed. Thanks so much for all you guys do!

**Comment by Goldenfreddy0703** [comment]
Hey @ek19q want you to do me a favor cause its possible verizon is blocking nyaa mirrors. Does this website work? 

Yes or No

https://nyaa.iss.ink/

**Comment by Goldenfreddy0703** [comment]
Ok interesting, this could help with #69. If you don't mind later, I'm gonna have you test a few nyaa mirror sites so that we know which ones work with and without firestick. Thank you for testing the site on firestick, helps alot to know what works and what doesn't work on other devices.

**Comment by Goldenfreddy0703** [comment]
Ok so you don't have to do all of them but find a few proxies that work with firestick and hopefully that should fix most firestick and nvidia bugs for Verizon Users. 

https://nyaatorrents.info/#proxy

**Comment by ek19q** [comment]
I had some free time so I just tested all of them. I threw the results in a spreadsheet. Hope this helps!

[Nyaa Proxies Testing (Firestick)](https://docs.google.com/spreadsheets/d/e/2PACX-1vT37R7f-jilkaNHmxu1b0ASd9lpbm7ajAo6KkmKzKKQgnBJ3gzqDjgx_m3gLeWsPVoXyPrzoe8lhIqI/pubhtml)

**Comment by Goldenfreddy0703** [comment]
Ok wow, didn't think you would test every link and put it in a spreadsheet, This helps a ton, thank you so much. For today, im going to try to make a temporary fix if possible in about 10min and make a release and hope this will help. 

Again, Huge thanks for testing this and huge thank you for putting it in a spreadsheet.

**Comment by ek19q** [comment]
No prob! I'm a dev myself so I know how these things go. I want to see this app succeed so I didn't mind helping. 👍🏾

**Comment by Goldenfreddy0703** [comment]
Ok well sad news, i tried replacing the ones that did work and sadly, they did not work but i do have one trick up my sleeve and it may work for your firestick. 

Are you able to access this site on your pc or firestick?
https://nyaa-si.translate.goog/?_x_tr_sl=es&_x_tr_tl=en&_x_tr_hl=en

We basically just used google translate sense its basically a proxy.

**Comment by ek19q** [comment]
Okay. Looks like I made a blunder during my testing. The Google translate sites do work. I thought with the way the page formatted itself it wasn't a working solution. The link you just sent works on both the PC and the firestick. 

I also went back and retested the other "translation" links and updated the spreadsheet with my original tests. You should be able to view the updates with the original link.

**Comment by Goldenfreddy0703** [comment]
> The link you just sent works on both the PC and the firestick.

Ok good then we have a permanent solution where Verizon can't block google translator site and that the Google translate sites do work. This should fix most issues with firesticks and nvidia sheilds. 

Thank you very much for your help. Will make a release in a few min!!!!

**Comment by Goldenfreddy0703** [comment]
Ok release should be online in a few seconds, pls go ahead and test on your firestick and tell me if everything works out for you.

**Comment by ek19q** [comment]
Hmm so far not working. But I also didn't get any updates in the changelog either so idk if the update pushed through to my end yet. I'll keep trying periodically and let you know if anything changes.

**Comment by Goldenfreddy0703** [comment]
Update my repo by reinstalling it or find the check for updates button where you go to my addons ect.

**Comment by ek19q** [comment]
Success! We are back in business!

**Comment by Goldenfreddy0703** [comment]
Nice glad to hear that. I'm going to go ahead and close this issue but huge thank you for all your help and helping resolving the Verizon issue. Now Verizon users won't have any more bugs with Otaku. If you ever like to contribute more, feel free to join our team and we can work together on making new features and stuff. My contact is in the readme and we will be glad to have you on our team someday.

Thank you
