### ISSUE TITLE
Bastard anime not showing full episodes

### ISSUE THREAD

**Issue by TaiDak** [Goldenfreddy0703/Otaku#129]
Not a major issue (in my opinion)
Noticed that the episode list for Bastard is 13 episodes,  but 24 were released. I looked it up and and Netflix released them in two parts, although they're both season 1. Wouldn't be an issue although it seems that Kitsu and MAL considers these two parts to be separate and this require a part 1 and part 1 on their websites. Anilist doesn't and instead says that there's 24 episodes. It appears that when the episode list is being built, it uses sources that tell it that it's part 1 with 13 episodes, I tried searching inside otaku for part 2, but the search only give me Anilist results. I tried getting around it by adding Bastard part 2 to my kitsu, and accessing it in Otaku, but all I get is an error.

**Comment by Goldenfreddy0703** [comment]
Ok weird, usually our anime database is from anilist is it should be in parts. I will look into that soon. Thanks for pointing this out.

**Comment by Goldenfreddy0703** [comment]
Hey so from loioking at this issue, this is quite interesting and it should have been an anilist error on there part sense kitsu and mal considers these in two parts,. Our episode meta comes from consumet or enime and somehow this anime has all 24 episodes.

Hopefully it can be fixed in the future but for a workaround go on the kitsu site and add part 2 of Bastard to your watchlist and hopefully that should fix it. 

Im going to go ahead and close this issue but is problems still persist. Pls feel free to respond in this issue and i will open it back up and investigate further.

**Comment by TaiDak** [comment]
Yeah, I already said that doing that causes an error, anyways, not your fault, it's the way different anime sites track episodes. Record of Ragnarok season 2 part 2 episodes don't show up, I can trick it by using the next up menu
