### ISSUE TITLE
Better Skip Intro Dialog

### ISSUE THREAD

**Issue by snoweuph** [Goldenfreddy0703/Otaku#14]
The Current Skip intro dialog just pops up on starting of a new episode and then if used skips a fixed amount of time.

It would be cool to have it skip perfectly, but that would need some kind of database storing the intro time frame for each episode.

Instead I would ask for some improvements of it that can be done without it:

- Configureable time till the popup to skip pops up (some anime always have first 2 minutes and then the intro rolls)
   

- Configureable Times for  **each anime**.
(Time till skip popup, time to skip)
(Some animes play the intros after 30seconds others after a minute, but overall it's mostly stays the same for the anime itself (though there are some small expetions)

- skipt hotkey button
( A Configureable button that's needs to be pressed to skip)
(I would let people chooses wether they just want to have it to be pressed once, if they want it to just open the Skip intro dialog or if they want to need to hold it (and how long))

I think these things would be a great improvement for the overall feeling

**Comment by Goldenfreddy0703** [comment]
Hey so from looking at your feature request, I do like some of the improvements but about that database storing the intro time frame, it would probably be impossible for us to add sense there is no database about that anywhere. 

Configureable time till the popup to skip pops up
- I see what you mean on that you would probably have to change that option repeatably for other animes. (That's why the intro skip is small so that you can still watch the anime)

Configureable Times for each anime.
- I think Configurable Times for each anime would be a hassle tbh if we added that. 

skipt hotkey button
- I think its a great idea but i don't think we could add something like this sense hot keys are handled by kodi itself and not the addon. 

Sorry to put down your ideas but i will ask what our team thinks about these.

**Comment by Goldenfreddy0703** [comment]
Hey so about this Better Skip Intro Dialog, we think its fine the way it is, Some animes are different then others and we just think its good to way it is. 

I'm going to go ahead and close this issue but if you would like this issue reopened and wanna talk about this more, Pls feel free to contact us and we will get to you when we are not busy.

**Comment by snoweuph** [comment]
Okay, Thx for your Feedback.
If for whatever reason reopend it prolly would be better of in Discussions then Issues.

I understand the reasoning for all the stuff, its a little bit sad, but thats just how it is. :)
