### ISSUE TITLE
Meta bug 

### ISSUE THREAD

**Issue by Thor4201** [Goldenfreddy0703/Otaku#154]
![Screenshot_20230918_165754_Kodi](https://github.com/Goldenfreddy0703/Otaku/assets/46413643/1f4c6066-2d87-4235-abf6-5ecadf89770a)
I noticed it first on my computer as it displayed the episode names before for this series "am I actually the strongest" so I did a little messing about on my phone and once I rebuilt the database or delete the database the names of episods for certain shows that previously displayed information disappeears ex of what I mean below, I've tried several things to fix it but I'm not too sure Kodi 20 btw 
![Screenshot_20230918_170434_Kodi](https://github.com/Goldenfreddy0703/Otaku/assets/46413643/3a589a1c-b95d-4e04-9502-643be6842131)

**Comment by Goldenfreddy0703** [comment]
Hey so Otaku episode meta providers are kinda under attack as we speak due to enime shutting down and stuff and now we are only using simkl for episode meta fallback. We hope to implant new episode meta or a new systhem to atlease get episode title, description, thumbnails, and lastly updates. This might our watchlist recode behind tho sadly but we are gonna have to see.

**Comment by Goldenfreddy0703** [comment]
Hey so i was right, this kinda diid put us behind a bit but we will hopefully be making a release hopefully in a day or two im going to consider this in progress but it will be fixed tomorrow or soon hopefully.

**Comment by Goldenfreddy0703** [comment]
Hey so good news, Major Watchlist Update should fix this issue and should be out, just make sure to rebuild database. If problems still occur please feel free to open this issue and we can look through it.
