### ISSUE TITLE
Arctic Fuse next up window

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#181]
Will there be an arctic Fuse next up window?

**Comment by Goldenfreddy0703** [comment]
Great question, I wish but in order for me to add that, I would need to get artic fuse for Seren working first, only problem is I cannot get the buttons working due to how jurialmunkey coded the next up parts in the skin. He had next up combined with some other code and it was complicated to separate. 

https://github.com/Goldenfreddy0703/seren.theme.af

Now if anyone is willing to fix the buttons in my Artic Fuze repo. I will definitely make it work in Otaku.

**Comment by Liquidrag** [comment]
Damn I wish I knew how to help

**Comment by Goldenfreddy0703** [comment]
Mmmm.....I may have an idea but he might be busy.

@jurialmunkey hey, sorry to bother or ping you but I have been having a bit of trouble getting buttons for the next up working in Seren, I am using the correct id's and everything but I don't know why buttons are not working for next up. I tried my best extracting some of your next up code from your Arctic Fuze skin but it was kinda hard sense you combined xml files for next up. 

Would it be alright if you could send me a single xml file of the next up from your Arctic Fuze Skin, I would definitely appreciate it and alot of people would greatly benefit from it. 

If you could that would be amazing.
Thank you and again, sorry for bother you. 

Here is what I have so far:
https://github.com/Goldenfreddy0703/seren.theme.af

**Comment by jurialmunkey** [comment]
@Goldenfreddy0703 - I'm a bit confused why you need everything in a single file?

The Up Next theme for AF reuses skin elements, I'm not sure why you can't do the same for another addon?

Judging from the screenshots, it looks like you're trying to recreate the AH2 theme instead of making the AF theme. You're going to have a bad time trying to do that because those elements don't exist in the same way in AF.

The AF theme for the Up Next addon has a completely different layout and button style. The styles you are trying to use are AH2 styles, not AF styles.

You can find the code here: https://github.com/jurialmunkey/skin.arctic.fuse/blob/ca874b0a185a29079701574a13f5bd1fec98cb1e/1080i/Includes_OSD.xml#L4-L163

As you can see, it is a completely different code layout to what you're using.

For reference, this is how Up Next should look in AF:

![screenshot00262](https://github.com/Goldenfreddy0703/Otaku/assets/4618719/dcb49e4c-ac6f-414e-bff0-b18a2cb496e5)

**Comment by Goldenfreddy0703** [comment]
Hey @jurialmunkey thank you very much for responding. In the project i provided, the screenshot just had not been updated yet to Arctic Fuze which is why it looks like an Arctic Horizon 2 theme, sorry about that. 

About the link you told me where to find the code, thats actually the code i used but i had trouble extracting lines 4-163 in your Includes_OSD.xml into a single file. Its different from how you originally coded it cause in AH2 you had the next up into a single xml file, and in AF you had the next up into a single file but had multiple includes and all. 

This was the file i tried to add lines 4-163 from your Includes_OSD.xml file but just failed to get the buttons working. I'm not sure what i did wrong in this file but if you can help me get the buttons working, That would be amazing. 
https://github.com/Goldenfreddy0703/seren.theme.af/blob/main/resources/skins/Default/1080i/playing_next.xml

**Comment by jurialmunkey** [comment]
There's a lot wrong with that file. Parts of it aren't even valid skin code.

You can't include content but then also attempt to define code inside it. You are mixing up include definitions and nested includes. This is not valid skin code.:

https://github.com/Goldenfreddy0703/seren.theme.af/blob/247a801c0c2792ddc4fa26e1bf7577f590274fad/resources/skins/Default/1080i/playing_next.xml#L8-L18

Secondly, buttons controls are not includes and cannot have params. These are not valid button controls:

https://github.com/Goldenfreddy0703/seren.theme.af/blob/247a801c0c2792ddc4fa26e1bf7577f590274fad/resources/skins/Default/1080i/playing_next.xml#L45-L62



Based upon what's in your file, I'm assuming you're trying to do this:
https://gist.githubusercontent.com/jurialmunkey/a501c8ecfe759d5e4a74b894d22d0347/raw/ccb268c3445d99cd994e7a8f009289f928c02321/playing_next.xml


Completely untested and entirely based upon what you've written in your code but at least it is valid skin code and so will get you 10x closer to something workable.

All I did was copy the content of the include into the file then find and replace $PARAM[] with the values you seem to be wanting to use. That's all $PARAMs do essentially anyway -- they just copy/paste raw text into the include content so you don't need to retype code.

I've set your button IDs to 3001 and 3002 because it seems like that's the ones you want to use.

**Comment by Goldenfreddy0703** [comment]
Omg yes, this is what i have been trying to do and its perfect. Thank you so much for doing this and thank you very much for pointing out some of the mistakes i made with it. Im not good at editing xml files most of the time but i am trying to learn how people edit them and all. 

Again, huge thank you so much copying the contents and getting the buttons working and all. You are the best and i am very happy with this. Now People who are using Seren or Otaku can use this them for play next with AH which is amazing.

Again, huge thank you!!!!!!

**Comment by Goldenfreddy0703** [comment]
Heyyyy @Liquidrag great news, i manage to get the Arctic Fuze next up window working for Otaku and it should be released. Im gonna go ahead and close this issue but if you run into problems with it, please feel free to message in here and we will open this issue back up. 

Thank everyone!!!!

**Comment by Liquidrag** [comment]
Thank you @jurialmunkey and @Goldenfreddy0703
