### ISSUE TITLE
Improper title/wrong scraping 

### ISSUE THREAD

**Issue by Hoogadabah** [Goldenfreddy0703/Otaku#193]
I'm trying to watch tenchi muyo. It finds the anime, but doesn't have the correct series in there and only has Tenchi universe. There is also no standalone Tenchi universe link.

**Comment by Gujal00** [comment]
It scrapes fine. If you are trying torrents then it could be a issue, just enable embeds, gogo, aniwatch and animix all have sources
![screenshot00000](https://github.com/Goldenfreddy0703/Otaku/assets/17394059/3727338a-e876-413f-8154-16677eea6295)
![screenshot00002](https://github.com/Goldenfreddy0703/Otaku/assets/17394059/83f7da98-0b80-4dd3-8bc5-58a006421dc5)
![screenshot00001](https://github.com/Goldenfreddy0703/Otaku/assets/17394059/6ce47776-0740-4c04-9614-a10906b44e30)

**Comment by Goldenfreddy0703** [comment]
Hey so from doing research, turns out Tenchi muyo is the same as Tenchi Universe. Anilist is a bit different then other databases due to there improper titles and all. 

Anilist: https://anilist.co/anime/696/Tenchi-Muyou/watch
Mal: https://myanimelist.net/anime/696/Tenchi_Muyou
Simkl: https://simkl.com/anime/40056/tenchi-muyou/episodes/

Im going to close this mark as complete but if you have any other questions or issues, feel free to reply here and we will look into it. 

Thank you
