### ISSUE TITLE
Turn off Auto Selection of Source

### ISSUE THREAD

**Issue by JSilver52** [Goldenfreddy0703/Otaku#195]
Hi  Goldenfreddy0703,

I really appreciate the work you've done on this addon. However, I find that the automatic selection and play of a source creates problems. Many times it seems to select the largest possible source which can cause problems for slower connections (and I mean enormous file sizes in the 10's of gigs). It also at times auto selects the wrong file from the source altogether, and instead of playing for instance episode 1 of season 1, plays episode 1 of season 2. I'm not sure if maybe the source has things labeled incompatibily. 

If there just a way to turn of the auto selection and allow the user to select the source manually that would be extremely helpful. If this option exists, I haven't been able to find it.

Thanks,

**Comment by Goldenfreddy0703** [comment]
Go to the general playback category of Otaku settings and you should see two settings uptop for TV shows and movies, put the TV shows to select source and that may resolve your issue.

About the scrapping, sometimes scrapping by title can not always get you the right results which is why you get different sources, what I suggest is either using embeds like aniwave or aniwatch or find batch torrents and all.

**Comment by JSilver52** [comment]
The settings to change are,
"Movie Play Style"
"Episode Play Style"

Thanks,

**Comment by TwilightMercy** [comment]
I would suggest to change auto selection to OFF by default
