### ISSUE TITLE
More Artwork Options (banner especially)

### ISSUE THREAD

**Issue by MightyMase04** [Goldenfreddy0703/Otaku#236]
Wondering if more options could be added for banner artwork. As is, each show only pulls a handful of fanart files and displays them randomly. 

Would it be possible to add an option to just display the official art banner everywhere? That's currently how Fen does it, but who knows if that's attainable for this project. 

Unless I'm missing a feature like this already, but I don't think so.

**Comment by Goldenfreddy0703** [comment]
Hey so I'm actually not sure on what your asking. We get our fanart from fanart to and our posters and banners from anilist. What type of options are you thinking?

**Comment by Goldenfreddy0703** [comment]
Ahhh I see what you mean now, yeah it's likely not possible to pull right Artwork from an anime. Reason why is due to lack of information of the anime which is why we basically either do a slug search or search by id. Sometimes clear logos can be different for seasons and may not be correct seasons and all and yeah.

I think I may have an idea on how we possibly could get specific but I'm going to have to look into the tvdb api and see if there is a way to get Artwork by season. It's possible tvdb api could provide so we will look into this and see if it's possible.

**Comment by Gujal00** [comment]
Not fair comparing anime addon such as Otaku to FEN/Seren. Can Fen/Seren find consistent sources for all anime? sameway Otaku cannot find consistent artwork for all Anime.

**Comment by Goldenfreddy0703** [comment]
> Can Fen/Seren find consistent sources for all anime? 

Unfortunately Yes cause they're databases are either trakt, tmdb, or tvdb which are quite the same. There Animes are not into split seasons or parts like ours which is why they have it easier to find Artwork for them. 

> sameway Otaku cannot find consistent artwork for all Anime.

I actually managed to find a way but may take more research. Tvdb has artwork types and one of those artwork types are clear logos that match the anime and seasons. The only research I need to do is how to get the artwork type from using our tvdb id's or season numbers in our database. 

Also btw, I'm not sure if we did this but fanart tv accepts tvdb and imdb id's if I recall, if we haven't already, we should let our database utilize them. If we already have that implemented, I must have forgotten unfortunately 😅

**Comment by Goldenfreddy0703** [comment]
Heyyyy so good news about clearlogos and hdtvlogos, sense we were unable to tell which logos goes with which season, we decided to have it show the first original logo for each season instead. Reason why is cause global databases that Fen, Seren, Tmdb helper have are logos that are based off of the original main show so we decided to follow there concept where any anime with a season will show the original logos, not the seasonal logo. Again, we are unable to tell which logo goes with which season and we decided to do this instead. 

Now about banners or fanart, unfortunately its not possible to get unique banners or fanart for each episode nor season cause again, fanart tv or tvdb or tmdb are unable to tell us which art goes which which season or which episode cause with a global database, its all a collection so its not possible sense we use a anime database. 

In a few min, we are going to go ahead and release so make sure you rebuild your database and you should be good. For animes with season, you should see its original logo, not random season logos so that its more accurate. Huge thanks for @Gujal00 for coding this logic in and hope this is more accurate then having random logos. 
Thank you!!!!

**Comment by MightyMase04** [comment]
Awesome, glad to hear it! I appreciate the work y'all do!
