### ISSUE TITLE
Titian Bingie Mod season and episodes selection in Bingie Info screen  with Otaku.  

### ISSUE THREAD

**Issue by minhgi** [Goldenfreddy0703/Otaku#273]
Wonder if this could be done?  Pulling the anime metadata so the seasons and episodes are shown together in the Bingie Info screen.  Guess this will be an enhancement? 

Here the anime "Attack of Titian" metadata is pull using Bingie Mod skin and TheMovieDB Helper addon.
![2024-06-04_120749](https://github.com/Goldenfreddy0703/Otaku/assets/4175702/375bf81d-e619-4346-994b-fbd040971fcd)

With Bingie Mod skin and Otaku addon.
![2024-06-04_120919](https://github.com/Goldenfreddy0703/Otaku/assets/4175702/358e8b03-9b1f-41b4-aebe-67f13d6cf815)

Can we receive the same result when using the skin and Otuka?  Maybe other skins could benefit as well if they have the same feature.

**Comment by Goldenfreddy0703** [comment]
Hey so when it comes to an anime database, seasons are all separated and all which is why seasons look like that, we could however have it show all seasons from one anime and utilize tvdb episode meta but it just wouldn't look right which is why all the seasons are in one. 

Anime databases and global databases do not really go well together.

**Comment by minhgi** [comment]
Yeah it wouldn't look jumbo up together.  It would cause excessive scrolling bc some anime of hundreds of episode.  Never mind.   I see why ur did for reason your did.  Research. ^_^

**Comment by minhgi** [comment]
Btw.  The workaround I found with my Trakt and MyAnimeList sync problem is to use Otuka player in TheMovieDB Helper.

**Comment by Goldenfreddy0703** [comment]
If it does help, in Otaku General settings we actually have a smart scrolling feature where it will automatically scroll the the episode you were watching. Hopefully that could help you out sense your on an anime with do many episodes. It's very useful.

**Comment by Goldenfreddy0703** [comment]
> Btw.  The workaround I found with my Trakt and MyAnimeList sync problem is to use Otuka player in TheMovieDB Helper.

It's some workaround but it's not always gonna work cause reason why is cause when it comes to tmdb, it's easy to convert mappings but it's not easy to convert episode numbers unfortunately cause tmdb may have different ways of how there episode meta is structured, same as trakt, and imdb. Are player does work for some animes but it will not work for most animes due to limitations. We wish there was a way to utilize tmdb without episode count but it's just not possible unfortunately.

**Comment by minhgi** [comment]
You are right. It's missed or hit using the player through the movie. TVDB/TMDB ID mis match.

**Comment by Goldenfreddy0703** [comment]
Hey so its possible i can look more into this in the future but it will take alot of time so i don't see this added anytime soon. If it does help, we actually do have a context menu item called get watch order where it grabs all the season and puts it in the watch order, hope this helps. Im going to go ahead and close this but if you have any questions or concerns, please feel free to ask and we will look into this further.

Thank you

**Comment by minhgi** [comment]
It is alright to close the ticket. Hope you get a solution in the future. Don't have to change anything. Thank you
