### ISSUE TITLE
✨️ Set Artwork for Fanart

### ISSUE THREAD

**Issue by Rinicko100** [Goldenfreddy0703/Otaku#276]
Hello, I was wondering if we could get the ability to set artwork for fanart and also to turn off the autorotate for fanart.

Some of the background fanart for some anime can sometimes be unnecessarily lewd, and because it auto rotates, it sometimes lands on the lewd ones, which can sometimes make things a little awkward if someone else stumbles on the setup, if you catch my drift.

Take this, for example
![Screenshot_20240607-145541.png](https://github.com/Goldenfreddy0703/Otaku/assets/172080110/1969e61e-40b8-44db-8022-226431fea55b)

That anime really has nothing to do with that... the fanart is borderline hentai😭😭... would like to be able to set one singular artwork for it

**Comment by Nuklear92** [comment]
Haha! I second this post. I was actually planning to create an issue based on this same situation. It's been a few times already that I have friends and family and since I have my setup with widgets in the homescreen some of them being from Otaku. There has been a few instances when some of these artworks show when scrolling around and they're a bit embarrassing when others ask me, "Hey! What is that" and I have to explain that are just random artworks that some of my anime tv shows display and they have nothing to do with the actual anime show. 😅

**Comment by Gujal00** [comment]
Just turn off fanart is settings if you dont want it.

**Comment by Nuklear92** [comment]
> Just turn off fanart is settings if you dont want it.
> 
> 

Sorry for my ignorance, but could you point me out where exactly in the  Otaku settings there's a fanart section to remove this explicit artworks. I, might had missed before. I've dug around all settings sections in order to remove these explicit landscape artworks and only show the official title artwork. Similar to if you would navigate and search for these anime shows in TMDb, Trakt, TVDb, etc. in the websites.

**Comment by Goldenfreddy0703** [comment]
Actually @Gujal00 we do not not have that option unfortunately, we do have is disabled when the user is scrapping but not when the user is viewing anime. We will make sure to implement that.

**Comment by Goldenfreddy0703** [comment]
Heyyy so about the Artwork for Fanart, we unfortunately could not hide the lewd fanart but we did however add 2 options to disable the fanart or clearlogo in Otaku's General Settings. We hope this works out well. 

In the future, we might add tvdb artwork as our primary source cause tvdb does not show lewd art, it will take time but we will add it eventually. Im going to keep this open but if you guys have any questions or concerns, please feel free to reply and we will get back to you. 

Thank you

**Comment by Rinicko100** [comment]
> Heyyy so about the Artwork for Fanart, we unfortunately could not hide the lewd fanart but we did however add 2 options to disable the fanart or clearlogo in Otaku's General Settings. We hope this works out well. 
> 
Really appreciate the effort 🙏🙏 and thanks for providing that option... 

> In the future, we might add tvdb artwork as our primary source cause tvdb does not show lewd art, it will take time but we will add it eventually. Im going to keep this open but if you guys have any questions or concerns, please feel free to reply and we will get back to you. 
> 
I was thinking it could be something similar to the way it is on tmdb helper or fen, where there's an option in the context menu to set artwork,  then it brings up a list of all the artwork, then you pick one to use

**Comment by Nuklear92** [comment]
> Heyyy so about the Artwork for Fanart, we unfortunately could not hide the lewd fanart but we did however add 2 options to disable the fanart or clearlogo in Otaku's General Settings. We hope this works out well. 
> 
> 
> 
> In the future, we might add tvdb artwork as our primary source cause tvdb does not show lewd art, it will take time but we will add it eventually. Im going to keep this open but if you guys have any questions or concerns, please feel free to reply and we will get back to you. 
> 
> 
> 
> Thank you
> 
> 
> 
> 

That would definitely be the best approach, as TVDb has a massive database for artworks and general information. Although, I don't know if you're planning to add TVDb only as the Artwork grabber from Otaku or also for general information regarding, episodes, shows, movies, etc. Since it's something I had noticed in otaku that some tv shows lack information regarding episode plots, artwork thumbs, among other things. 🤔

**Comment by Goldenfreddy0703** [comment]
Hey so sorry this took about a month but we have came up with a solution that might help. We have added a context menu called "Select Fanart" were the user can select the fanart for a specific anime so that way, if an anime has lewd art, the user can change it to something specific. 

To enable the context menu item go to your Otaku Settings > General > Context Menus and you should see and option to enable "Select Fanart" in context menu. 

It may not be the best solution but will help for specific anime. Feel free to test this, if you run into any problems related to this issue, please reply in here and we will look further into it. 
Thank you

**Comment by Rinicko100** [comment]
> Hey so sorry this took about a month but we have came up with a solution that might help. We have added a context menu called "Select Fanart" were the user can select the fanart for a specific anime so that way, if an anime has lewd art, the user can change it to something specific. 
> 
> To enable the context menu item go to your Otaku Settings > General > Context Menus and you should see and option to enable "Select Fanart" in context menu. 
> 
> It may not be the best solution but will help for specific anime. Feel free to test this, if you run into any problems related to this issue, please reply in here and we will look further into it. 
> Thank you

Really appreciate this addition... it's a perfect solution for this. Thank you for your continued effort in advancing this addon
