### ISSUE TITLE
CRASHING ERROR

### ISSUE THREAD

**Issue by XHALOX18** [Goldenfreddy0703/Otaku#287]
The kodi would crash  I didn't enable hd-1 and yes I cleared cache and torrent the embed would just crash my kodi the only way I can watch anime is by disabling all embeds and  use the real-debrid also my caching setting for my kodi is maxed out just wanted to state that I don't know if that affects it

**Comment by Goldenfreddy0703** [comment]
Mmm....would you mind sending a log maybe. Its possible that the crashing issue could be related to either your kodi device depending on what your using or it could be your wifi router cause sometimes Otaku requires a good connection in order to work with embeds and torrents and all. 

You may want to experiment a bit and see which provider works and which one doesn't and hopefully we could find the culprit. If your using an nvidia shield, its also possible you may need to disable ipv6 cause most people with shields have alot of issues. 
Hopefully this helps. 

Oh also doing a complete reinstall mostly fixes most issues so try that if you havn't already.

**Comment by XHALOX18** [comment]
1gb WiFi speed using a above average gaming pc and I reinstalled it didn't change but thing I also noticed they would only crash for fairy tail and Pokemon I can watch other anime on it

**Comment by Goldenfreddy0703** [comment]
Wired, may want to look into it sense your using a gaming pc and that it would only crash Pokémon or Fairy Tail.

**Comment by Goldenfreddy0703** [comment]
Hey so we recently, fixed 289 and made a release, see if our latest release fixes your issue, if so then we will close this. 

Thanks

**Comment by Goldenfreddy0703** [comment]
Hey so sorry its been about a month but i think i might know whats causing most the crashing issues and it has todo with InputStream Adaptive. Do me a favor and reinstall InputStream Adaptive and that should hopefully fix your issue. 

Im going to go ahead and close this but if issues still persist, we will looks into it.
Thanks
