### ISSUE TITLE
Otaku not letting me authorise simkl

### ISSUE THREAD

**Issue by GitHubSand** [Goldenfreddy0703/Otaku#307]

**Comment by Goldenfreddy0703** [comment]
Hey so from looking at #306 and #307, it seems to look like your having connection issues especially if you can't connect to simkl.

You may wanna try these things to get your Otaku working depending on your device:
- Clear Cache, Torrent Cache, Rebuild Database
- Restart your device or try another device to see if issue still persist. 
- Restart your router by unplugging it and plugging it back in.
- On your device, try disabling ipv6 cause ipv6 causes most of the issues.
- You router could be blocking certain sites such as simkl so see if you can access the site:  https://simkl.com
- If your using an apple device, apple devices tend to not work well with kodi due to apples restrictions.
- If none of these steps are working, try looking through the troubleshooting steps: #15

**Comment by GitHubSand** [comment]
I can connect to it I even have the app it's just when I go to authorise it, it will give me a code to sync the account for about ten seconds then say there was a problem

**Comment by Goldenfreddy0703** [comment]
Interesting, could you possibly send me a log of the error.

**Comment by GitHubSand** [comment]
![image](https://github.com/user-attachments/assets/a832a6e8-8309-4794-a88e-d34d2238b485)

**Comment by Goldenfreddy0703** [comment]
ok for some odd reason, i think it could be due to your connection. Ok so you said you can connect to it and you even have the app but is there a small possible chance that you tried to connect to it through your phone using mobile data? If so could you try connecting to it on your computer just incase? If so that would help, thanks

Also what device and kodi version are the using?

**Comment by GitHubSand** [comment]
Simkl works fine with other Devices and I'm using an Xbox s series

**Comment by Goldenfreddy0703** [comment]
Ohhhhhh that could explain alot. I forgot the Xbox does not work well with kodi either due to its limitations.

**Comment by Goldenfreddy0703** [comment]
@Gujal00 if you don't mind, could you see if you can replicate this issue on xbox? If you could that would be great.
Thanks

**Comment by jewbmx** [comment]
If you need another way to test your issue id suggest looking for the "addon" script.simkl which seems to work just like script.trakt lol.
So if you can install script.simkl and get your account working in it there might be a bug to fix in otaku, if it fails then it might be a issue on your end. Oh and if that addon isnt something you wanna use id suggest deleting it afterwards so you dont have issues down the road. (Like duped process bugs where 2 addons are doing the same thing.)

**Comment by jewbmx** [comment]
Hey @Goldenfreddy0703 , sorry for the name tag but thought itd be easier then typing your name out lol.
I found something nice while tinkering with the simkl api. Instead of using the client id in everything like they tell you to, you can actually just add that header line they offer that includes the client id. I also figured out their client secret is not needed but you probably already knew that bit. Also not sure if its different for other folks but on the pin url for me it didnt have a place to put the user pin just a yes or no option for pairing the account to the addon lol. Which makes me wonder if the pairing process instructions should be modified to match the steps. (Telling you this extra bit since i sorta copied your process when doing my own lol.)
