### ISSUE TITLE
Update for Dubbed Fonts

### ISSUE THREAD

**Issue by antoniem34** [Goldenfreddy0703/Otaku#313]
For now, the addon only has the option to choose between Japanese and English in the settings.

But there are already many multi-audio sources, which include several languages, but unfortunately we cannot choose them automatically from the addon.

These sources are usually identified with the words Multi-Audio.

Example: 

- [ToonsHub] Demon Slayer Kimetsu no Yaiba S05E06 1080p AMZN WEB-DL DDP2.0 H.264 (Multi-Audio, Multi-Subs) 
- VTuber.Legend.How.I.Went.Viral.after.Forgetting.to.Turn.Off.My.Stream.S01E01.720p.CR.WEB-DL.MULTi.AAC 2.0.H.264-NanDesuKa.mkv 
- Ninja Kamui - S01E10 - MULTi 1080p WEB H.264 -NanDesuKa (HMAX).mkv

![image](https://github.com/user-attachments/assets/c9e34446-e630-463c-afbb-ec9e210e1c38)

**Comment by Goldenfreddy0703** [comment]
Mmmmm....ok I see what you mean, we could probably add more languages to it but a long time ago, I had a reason why I only had it to English or Japanese and that probably had to do with either figuring out if subtitles should be enabled or not or something with dual audio sources. I don't remember exactly but I could probably add more languages maybe. The only downsides with this is that most of the embeds and anime torrents don't even offer other audio languages, mostly English and Japanese torrents and I never seen any torrents that have Multi-Audio which is interesting from your screenshot. Ok do basically the only torrents you will most likely see if it was a different audio language is duel-subs and multi-audio.

**Comment by Goldenfreddy0703** [comment]
[image](https://github.com/user-attachments/assets/473ff5c9-5f9c-48be-9a4f-0a4f8509c7dc)

From your image I can also add Multi Audio, I didn't even know that was even a thing.

**Comment by Goldenfreddy0703** [comment]
Heyyyy so i made a release that should add Multi Audio so tell me if it works out for you but if not, tell me what animes that have multi audio so i can test them and everything. 

As for the audio language, i did not work on that cause i just remembered why i only set it to eng or jpn and that reason is cause of sub and dub sources where if the user selected eng then dub sources would play english audio without subtitles, if the user wanted jpn then the sub source would play jpn audio without the subtitle, if the source was a duel audio then it would select the audio you picked but if eng or jpn was not one of them, it would probably default to the first one if im correct. I will still look into it more in the future and all and see what i can do. 

Im gonna go ahead and close this but if issues still occur, feel free to reply and we will open this back up and look further.
Thank you
