### ISSUE TITLE
[Request] Rezise for wider text view on Video Selection

### ISSUE THREAD

**Issue by Nuklear92** [Goldenfreddy0703/Otaku#330]
Hello, I was wondering if it's possible to resize the video Selection wider in order to be able to view some Batch/Season Packs that have long text before showing you which Episode number. As you'll see in the clip below, the first Season Pack I select to view I have to wait a bit in each link in order to be able to see which Episode number from the season it is. Whereas for the second season pack I select the, the way the uploader organized into fewer text words you can easily see at a first glance each episode number.

So, the point of this post is pretty much in order to make the video selection box UI wider in general, so, in situations where you select certain season packs that have too many text, at least you're able to see the episode number before the text cut out at a first glance. Instead of having to wait for text to scroll which can take quite some time if you add up scrolling to each link + wait to see the correct episode number.

Hopefully, you understand what I meant. Here's the clip below so you can see the difference between the first season pack I select, compared to the second one. By the way this is having the option turned on for "Manual link selection" for BATCH/Season Packs.

https://streamable.com/h2uni7

**Comment by jewbmx** [comment]
I think you might be able to tinker with that yourself if you have access to the addon files, pretty sure the design is a skin layout type of thing so the addon should have a file somewhere for its source select where you could modify the numbers a bit. Or you could try finding the spot where the label gets its bold code and remove that in order to have it show a little more in the line.
I dont see your request being fulfilled tho by the dev since i think the layout is quite nice on its design. (ocd opinion lol)
Maybe just adding a some text option settings could fix the problem tho like letting anyone toggle off the bold or even just adding another info slot to display the season/episode bit like it does in the top right above the pic.

**Comment by jewbmx** [comment]
Id honestly just choose a different source that has a better label design instead of that bulky first choice lol. His labeling skills are the real issue :)
