### ISSUE TITLE
Problem with the movies and shows in

### ISSUE THREAD

**Issue by Adu185** [Goldenfreddy0703/Otaku#340]
Hey, sorry I didn't get back to you, but I'm still having the same problem. However, there's another movie that has the same issue: Dragon Ball Battle of Gods is unavailable to watch. Also, the two Quintessential Quintuplets specials don't seem to be working like the one from last year and the recent one. Sorry to bother you.

**Comment by Goldenfreddy0703** [comment]
Hey your fine, sometimes specials or dragon ball can have problems due to Anilist, this might be unfixable at the moment but in the future, we plan on fixing all the movie and tv database bugs so users can watch almost any anime without issues from anilist.

**Comment by Gujal00** [comment]
The specials are always hit an miss due to the way the sites name them and anilist names them
For e.g., this is what H!anime has for Anilist title Romaji: `Go-toubun no Hanayome * `  and English: `The Quintessential Quintuplets*`
`title="The Quintessential Quintuplets: The Movie" data-jname="5-toubun no Hanayome MOVIE"`
The title cannot match both english or romaji, so can;'t do anything about it.

Same issue with Dragon Ball movies. every embed site has the movie number inside the title which Anilist doesnt. so can't match 
Anilist:
```
Romaji
Dragon Ball Z: Kami to Kami
English
Dragon Ball Z: Battle of Gods
```
Every embed site out there has it as `Dragon Ball Z Movie 14: Battle of Gods` and `Dragon Ball Z Movie 14: Kami to Kami`

**Comment by Adu185** [comment]
Nws that's fine. I think I might have realized the problem, its looking for the show in dub, and I'm pretty sure there is only sub for the specials.
