### ISSUE TITLE
Question about trakt

### ISSUE THREAD

**Issue by Liquidrag** [Goldenfreddy0703/Otaku#35]
In the change log it mentions trakt search and rescrape. How does this work? How do I pair it with my trakt account?

**Comment by icpryde** [comment]
The trakt part is for meta data it’s not for connecting your trskt account, as far as I know that won’t really be possible people trakt is horrible with anime.

you are best to use Anilist or MAL to track your anime.

**Comment by Liquidrag** [comment]
Thnk you, I have all 3 and is syncing to anilist already, I just saw trakt and was wondering how it worked. Thank you.

**Comment by joezito129** [comment]
Is there a reason we are parsing the metadata from trakt instead of simkl?

**Comment by Goldenfreddy0703** [comment]
Big reason why we parse trakt then simkl is due to quality, Simkl provides function and that's good but most of the time, it does not offer thumbnails.

**Comment by Gujal00** [comment]
> In the change log it mentions trakt search and rescrape. How does this work? How do I pair it with my trakt account?

If you are wondering about trakt scrobbling, then yes the Kodi official trakt addon if installed and paired, will scrobble anything being played. It works for a lot of anime but not all.

trakt scrape in otaku is used to find the tmdb and tvdb mappings so that artwork from fanart.tv can then be downloaded.
