### ISSUE TITLE
Trakt script addon not recognizing Otaku when using MAL's Next Up

### ISSUE THREAD

**Issue by Nuklear92** [Goldenfreddy0703/Otaku#97]
As the title says, I'm currently signed in with my MAL (MyAnimeList) account in Otaku. When I use the Next Up inside the MAL menu, when I select my next up episode for example; Bleach EP.56. The Trakt script doesn't recognize when I stream the episode after selecting a source from Scraping UI, therefore it doesn't Scrobbe the Ep. I have to manually search the show, from the Otaku Search option above the Tools and look for the Bleach TV Show, then look for Episode 56 from there and that way the Trakt script addon will recognize it and start scrobbing. 

I'll leave a debug log below, maybe you can see if there's an issue or something. It happens with any show I have in MAL and when you direct stream the Ep, via the Next Up in the MAL menu or even using the MAL Next Up as a homescreen widget.

https://paste.kodi.tv/ruzofobope

**Comment by Goldenfreddy0703** [comment]
Ok, I ignored your long message and looked at the title and I'm just gonna tell you, Otaku does not support Trakt even if you use the Trakt Script addon. Otaku has a totally different database cause it's using Anilist, Trakt does not support anime from Anilist, Mal, or Kitsu. It's technically impossible due to season parsing and they are totally different databases. If I were me, I would either use Anilist, Mal, or Kitsu to track your anime then trakt. 😂

**Comment by Goldenfreddy0703** [comment]
Ok, I ignored your long message and looked at the title and I'm just gonna tell you, Otaku does not support Trakt even if you use the Trakt Script addon. Otaku has a totally different database cause it's using Anilist, Trakt does not support anime from Anilist, Mal, or Kitsu. It's technically impossible due to season parsing and they are totally different databases. If I were me, I would either use Anilist, Mal, or Kitsu to track your anime then trakt. 😂
